name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: "e.g. search_audio returns empty results for a file that clearly contains the keyword"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `augent search audio.mp3 "keyword"`
        2. See empty results
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: dropdown
    id: mode
    attributes:
      label: How are you using Augent?
      options:
        - Claude Code (MCP)
        - CLI
        - Web UI
        - Python API
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "e.g. macOS 15.1, Ubuntu 24.04, Windows 11"
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "e.g. 3.12.0"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Error output / logs
      description: Paste any error messages or relevant logs.
      render: shell
    validations:
      required: false
