name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What are you trying to do that you can't?
      placeholder: "e.g. I want to search across 50+ files but batch_search is too slow"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true
  - type: dropdown
    id: scope
    attributes:
      label: Area
      options:
        - MCP Tools
        - CLI
        - Web UI
        - Python API
        - Installation
        - Documentation
        - Other
    validations:
      required: true
